jobs:
    ci:
        if: github.event_name == 'pull_request' || github.event_name == 'push' || (github.event_name != 'pull_request_review' && github.event.review.author_association == 'MEMBER' && github.event.pull_request.title == 'Update pre-commit hooks')
        name: CI
        secrets: inherit
        uses: praw-dev-test/.github/.github/workflows/ci.yml@main
        with:
            package: praw
name: CI
on:
    pull_request_review:
        types: [ submitted ]
    pull_request:
    push:
permissions: read-all
