jobs:
    ci:
        name: CI
        secrets: inherit
        uses: praw-dev-test/.github/.github/workflows/ci.yml@main
        with:
            package: praw
name: CI
on:
    pull_request_review:
        types: [ submitted ]
    pull_request:
    push:
permissions: read-all
