jobs:
  pre-commit_autoupdate:
    name: Update pre-commit hooks
    secrets: inherit
    uses: praw-dev-test/.github/.github/workflows/pre-commit_autoupdate.yml@main
name: Update pre-commit hooks
on:
  schedule:
    - cron: 0/5 * * * *
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
