jobs:
  tag_release:
    name: Tag Release
    secrets: inherit
    uses: praw-dev-test/.github/.github/workflows/tag_release.yml@main
name: Tag Release
on:
  push:
    branches: [ master, release_test ]
permissions:
  contents: write
